version: "3.9"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"
    depends_on: 
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/my-mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db-script.js:/docker-entrypoint-initdb.d/init-mongo.js