services:
  - type: web
    name: portfolio-frontend
    plan: free
    runtime: node  
    repo: https://github.com/your-username/your-repo.git 
    buildCommand: "cd client && npm install && npm run build"
    startCommand: "python -m http.server -d client/build" 
    envVars:
      - key: PORT
        value: "3000"

  - type: web
    name: portfolio-backend
    plan: free
    runtime: node 
    repo: https://github.com/your-username/your-repo.git 
    startCommand: "npm start" 
    envVars:
      - key: PORT
        value: "5000"
      - key: MONGODB_URI 
        fromDatabase:
          name: portfolio-mongodb
          property: connectionString

  - name: portfolio-mongodb
    plan: free
    databaseName: my-mongodb 